import type { SkillContent, SkillMcpDependency } from '../skills/skills.dto';

/**
 * 内置技能种子（8.8 技能源「内置技能：本地预置，官方」+ 原型 9.1/12.1 的官方技能集合）。
 * 迁移/启动时按 slug 幂等插入（MarketService.seedBuiltins）：已存在即跳过。
 * status 一律 PUBLISHED、source='builtin'、publisher 为空（前端显示「官方」）。
 */
export interface BuiltinListingSeed {
  slug: string;
  name: string;
  description: string;
  category: string;
  tags: string[];
  type: string;
  license: string;
  compatible_clients: string[];
  mcp_dependencies: SkillMcpDependency[];
  current_version: string;
  content: SkillContent;
}

const CLIENTS = ['Claude Code', 'Qoder', 'Codex'];

/**
 * 已下架的内置技能 slug：不再随 seed 分发；MarketService.seedBuiltins 启动时会把
 * 残留的旧 seed listing 置为 DELISTED（幂等）。
 * - doc-generation：与 readme-generation/changelog-generation 职责重叠，且正文过薄
 * - regression-testing：与 unit-testing/release-checklist 重叠，正文不可执行
 */
export const DELISTED_BUILTIN_SLUGS = ['doc-generation', 'regression-testing'];

type SeedBlock = SkillContent['blocks'][number];

function block(block: SeedBlock): SeedBlock {
  return block;
}

/** 紧凑构造器：仅用于种子书写，产物结构与 block() 完全一致。 */
function p(id: string, title: string, prompt: string, to?: string): SeedBlock {
  return block({ id, kind: 'prompt', title, prompt, ...(to ? { next: [{ when: '', to }] } : {}) });
}
function st(id: string, title: string, steps: string[], to?: string): SeedBlock {
  return block({ id, kind: 'step', title, steps, ...(to ? { next: [{ when: '', to }] } : {}) });
}
function dec(id: string, title: string, condition: string, yes: string, no: string): SeedBlock {
  return block({
    id,
    kind: 'decision',
    title,
    condition,
    next: [
      { when: '是', to: yes },
      { when: '否', to: no },
    ],
  });
}
function hum(id: string, title: string, humanInstruction: string): SeedBlock {
  return block({ id, kind: 'human', title, humanInstruction });
}
function cons(id: string, title: string, rule: string): SeedBlock {
  return block({ id, kind: 'constraint', title, rule });
}
function inp(id: string, title: string, name: string, to: string, required = true): SeedBlock {
  return block({ id, kind: 'input', title, name, valueType: 'text', required, next: [{ when: '', to }] });
}
function out(id: string, title: string, name: string): SeedBlock {
  return block({ id, kind: 'output', title, name, valueType: 'text' });
}

export const BUILTIN_LISTINGS: BuiltinListingSeed[] = [
  {
    slug: 'code-review',
    name: '代码审查',
    description: '对代码 diff 做风格、安全、逻辑三层审查，输出结构化审查报告。',
    category: '质量保障',
    tags: ['review', 'quality', 'workflow'],
    type: 'workflow',
    license: 'MIT',
    compatible_clients: CLIENTS,
    mcp_dependencies: [],
    current_version: 'v1.0.0',
    content: {
      entryBlockId: 'b1',
      blocks: [
        block({
          id: 'b1',
          kind: 'prompt',
          title: '加载审查上下文',
          prompt: '阅读待审查的代码 diff 及其关联文件，理解改动意图。',
          next: [{ when: '', to: 'b2' }],
        }),
        block({
          id: 'b2',
          kind: 'step',
          title: '三层审查',
          steps: ['风格检查：命名、格式、注释规范', '安全检查：注入、越权、敏感信息泄漏', '逻辑检查：边界条件、错误处理、并发风险'],
          next: [{ when: '', to: 'b3' }],
        }),
        block({
          id: 'b3',
          kind: 'decision',
          title: '是否发现问题',
          condition: '审查发现需要修复的问题',
          next: [
            { when: '是', to: 'b4' },
            { when: '否', to: 'b5' },
          ],
        }),
        block({
          id: 'b4',
          kind: 'prompt',
          title: '输出问题清单',
          prompt: '按严重程度列出问题：位置、描述、修复建议。',
          next: [{ when: '', to: 'b5' }],
        }),
        block({ id: 'b5', kind: 'prompt', title: '输出报告', prompt: '汇总为审查报告：结论、问题清单、整体建议。' }),
      ],
    },
  },
  {
    slug: 'bug-fix',
    name: '缺陷修复',
    description: '根据缺陷描述定位根因、给出最小修复方案并验证回归影响面。',
    category: '质量保障',
    tags: ['debug', 'fix'],
    type: 'flow',
    license: 'MIT',
    compatible_clients: CLIENTS,
    mcp_dependencies: [],
    current_version: 'v1.0.0',
    content: {
      entryBlockId: 'b1',
      blocks: [
        block({
          id: 'b1',
          kind: 'step',
          title: '定位根因',
          steps: ['复现缺陷路径', '用二分法缩小可疑改动范围', '确认根因'],
          next: [{ when: '', to: 'b2' }],
        }),
        block({
          id: 'b2',
          kind: 'decision',
          title: '是否可最小修复',
          condition: '修复不超过三个文件且不改变对外接口',
          next: [
            { when: '是', to: 'b3' },
            { when: '否', to: 'b4' },
          ],
        }),
        block({
          id: 'b3',
          kind: 'prompt',
          title: '实施修复',
          prompt: '给出最小 diff 修复，并说明为什么该修复不会引入回归。',
          next: [{ when: '', to: 'b5' }],
        }),
        block({
          id: 'b4',
          kind: 'prompt',
          title: '升级处理',
          prompt: '修复面过大：输出修复方案设计与拆分建议，交给人工决策。',
        }),
        block({
          id: 'b5',
          kind: 'step',
          title: '验证',
          steps: ['针对缺陷补充回归测试', '运行相关测试套件'],
        }),
      ],
    },
  },
  {
    slug: 'unit-testing',
    name: '单元测试',
    description: '为指定模块设计并编写单元测试，覆盖正常路径、边界与异常分支。',
    category: '测试',
    tags: ['test', 'unit-test'],
    type: 'workflow',
    license: 'MIT',
    compatible_clients: CLIENTS,
    mcp_dependencies: [],
    current_version: 'v1.1.0',
    content: {
      entryBlockId: 'b1',
      blocks: [
        block({
          id: 'b1',
          kind: 'step',
          title: '分析被测代码',
          steps: ['列出公共接口与分支', '识别边界值与等价类'],
          next: [{ when: '', to: 'b2' }],
        }),
        block({
          id: 'b2',
          kind: 'prompt',
          title: '设计用例矩阵',
          prompt: '输出用例矩阵：用例名、输入、期望输出、覆盖分支。',
          next: [{ when: '', to: 'b3' }],
        }),
        block({
          id: 'b3',
          kind: 'prompt',
          title: '编写测试',
          prompt: '按项目既有测试框架与风格编写测试代码，mock 外部依赖。',
        }),
      ],
    },
  },
  {
    slug: 'performance-optimization',
    name: '性能优化',
    description: '分析热点路径，定位性能瓶颈，给出可量化的优化方案与验证方法。',
    category: '重构',
    tags: ['performance', 'profiling'],
    type: 'flow',
    license: 'MIT',
    compatible_clients: CLIENTS,
    mcp_dependencies: [],
    current_version: 'v1.0.0',
    content: {
      entryBlockId: 'b1',
      blocks: [
        block({
          id: 'b1',
          kind: 'prompt',
          title: '建立基线',
          prompt: '先运行/推演现有基准，记录耗时与内存基线数据。',
          next: [{ when: '', to: 'b2' }],
        }),
        block({
          id: 'b2',
          kind: 'step',
          title: '定位瓶颈',
          steps: ['按 80/20 找热点路径', '区分 CPU/IO/锁竞争', '量化每个瓶颈的耗时占比，排除猜测性结论'],
          next: [{ when: '', to: 'b3' }],
        }),
        block({
          id: 'b3',
          kind: 'decision',
          title: '瓶颈是否在系统边界',
          condition: '瓶颈位于数据库、外部服务、网络 IO 等代码层无法根治的边界（需缓存层/读写分离/换存储）',
          next: [
            { when: '是', to: 'b4' },
            { when: '否', to: 'b5' },
          ],
        }),
        block({
          id: 'b4',
          kind: 'human',
          title: '架构级优化确认',
          humanInstruction: '瓶颈在系统边界，架构级方案涉及成本与排期，请人工决策后再实施',
        }),
        block({
          id: 'b5',
          kind: 'prompt',
          title: '优化并复测',
          prompt:
            '对任务「{{task.title}}」逐项实施优化并复测，输出前后对比数据（耗时/内存，同基准同环境）；收益不显著或引入复杂度的优化回滚并说明取舍。',
        }),
      ],
    },
  },
  {
    slug: 'security-scan',
    name: '安全扫描',
    description: '按 OWASP 常见漏洞清单扫描代码与依赖，输出风险等级与修复建议。',
    category: '质量保障',
    tags: ['security', 'owasp'],
    type: 'workflow',
    license: 'MIT',
    compatible_clients: CLIENTS,
    mcp_dependencies: [],
    current_version: 'v1.0.0',
    content: {
      entryBlockId: 'b1',
      blocks: [
        block({
          id: 'b1',
          kind: 'step',
          title: '静态扫描',
          steps: ['注入类：SQL/命令/路径拼接', '越权与鉴权缺失', '敏感信息硬编码'],
          next: [{ when: '', to: 'b2' }],
        }),
        block({
          id: 'b2',
          kind: 'step',
          title: '依赖扫描',
          steps: ['列出直接依赖的已知 CVE', '评估可升级性'],
          next: [{ when: '', to: 'b3' }],
        }),
        block({
          id: 'b3',
          kind: 'decision',
          title: '是否存在高危项',
          condition: '发现高危或严重等级风险',
          next: [
            { when: '是', to: 'b4' },
            { when: '否', to: 'b5' },
          ],
        }),
        block({
          id: 'b4',
          kind: 'human',
          title: '人工确认',
          humanInstruction: '存在高危风险，请人工确认处理优先级',
        }),
        block({
          id: 'b5',
          kind: 'prompt',
          title: '输出报告',
          prompt: '按风险等级汇总：位置、漏洞类型、修复建议。',
        }),
      ],
    },
  },
  {
    slug: 'deployment-pipeline',
    name: '部署流程',
    description: '按检查单执行发布前检查、灰度发布与回滚预案演练。',
    category: '部署',
    tags: ['deploy', 'release'],
    type: 'flow',
    license: 'Apache-2.0',
    compatible_clients: CLIENTS,
    mcp_dependencies: [],
    current_version: 'v1.0.0',
    content: {
      entryBlockId: 'b1',
      blocks: [
        block({
          id: 'b1',
          kind: 'step',
          title: '发布前检查',
          steps: ['确认版本号与变更清单', '确认数据库迁移已评审', '确认回滚预案可用'],
          next: [{ when: '', to: 'b2' }],
        }),
        block({
          id: 'b2',
          kind: 'human',
          title: '发布审批',
          humanInstruction: '发布需要人工审批确认',
          next: [{ when: '', to: 'b3' }],
        }),
        block({
          id: 'b3',
          kind: 'step',
          title: '灰度发布',
          steps: ['小流量发布并观察核心指标', '逐步放量到全量'],
        }),
      ],
    },
  },
  {
    slug: 'commit-message',
    name: '提交信息生成',
    description: '读取 staged diff 生成符合 Conventional Commits 规范的提交信息，含正文与破坏性变更标注。',
    category: '开发流程',
    tags: ['git', 'commit', 'conventional-commits'],
    type: 'workflow',
    license: 'MIT',
    compatible_clients: CLIENTS,
    mcp_dependencies: [],
    current_version: 'v1.0.0',
    content: {
      entryBlockId: 'b1',
      blocks: [
        block({
          id: 'b1',
          kind: 'prompt',
          title: '读取变更',
          prompt: '执行 git diff --staged 阅读暂存区改动，归纳本次变更的目的与影响范围。变更说明：{{input.change_notes}}',
          next: [{ when: '', to: 'b2' }],
        }),
        block({
          id: 'b2',
          kind: 'decision',
          title: '是否为原子提交',
          condition: 'staged 改动只包含一个逻辑变更',
          next: [
            { when: '是', to: 'b3' },
            { when: '否', to: 'b4' },
          ],
        }),
        block({
          id: 'b3',
          kind: 'prompt',
          title: '生成提交信息',
          prompt:
            '按 Conventional Commits 生成：type(scope): 简洁祈使句标题（≤50 字符）；正文说明动机与副作用（≤72 字符/行）；破坏性变更标注 ! 与 BREAKING CHANGE。输出到 {{task.title}} 对应的提交。',
          next: [{ when: '', to: 'b5' }],
        }),
        block({
          id: 'b4',
          kind: 'human',
          title: '人工拆分确认',
          humanInstruction: 'staged 改动包含多个逻辑变更，建议按功能拆分后分批提交，请人工确认拆分方式',
          next: [{ when: '', to: 'b3' }],
        }),
        block({
          id: 'b5',
          kind: 'output',
          title: '输出结果',
          name: 'commit_message',
          valueType: 'text',
        }),
      ],
    },
  },
  {
    slug: 'readme-generation',
    name: 'README 生成',
    description: '从项目结构与代码生成结构化 README：简介、快速开始、配置说明与常见问题。',
    category: '文档',
    tags: ['readme', 'docs', 'onboarding'],
    type: 'workflow',
    license: 'MIT',
    compatible_clients: CLIENTS,
    mcp_dependencies: [],
    current_version: 'v1.0.0',
    content: {
      entryBlockId: 'b1',
      blocks: [
        block({
          id: 'b1',
          kind: 'prompt',
          title: '分析项目',
          prompt:
            '阅读 package.json/构建脚本与目录结构，识别技术栈、入口、构建与运行命令。项目路径：{{input.project_path}}',
          next: [{ when: '', to: 'b2' }],
        }),
        block({
          id: 'b2',
          kind: 'step',
          title: '提取关键信息',
          steps: ['项目定位与核心功能', '安装与快速开始命令', '必填环境变量与配置项', '已有 README 可保留的段落'],
          next: [{ when: '', to: 'b3' }],
        }),
        block({
          id: 'b3',
          kind: 'prompt',
          title: '撰写 README',
          prompt:
            '生成 README：项目简介、功能特性、快速开始、配置说明（表格）、目录结构、常见问题。语言风格与项目现有文档保持一致，命令必须来自真实构建脚本而非猜测。',
        }),
      ],
    },
  },
  {
    slug: 'refactoring-advice',
    name: '重构建议',
    description: '识别代码坏味道，给出分级重构方案、收益评估与安全的重构步骤序列。',
    category: '重构',
    tags: ['refactor', 'clean-code', 'code-smell'],
    type: 'workflow',
    license: 'MIT',
    compatible_clients: CLIENTS,
    mcp_dependencies: [],
    current_version: 'v1.0.0',
    content: {
      entryBlockId: 'b1',
      blocks: [
        block({
          id: 'b1',
          kind: 'prompt',
          title: '扫描坏味道',
          prompt:
            '阅读目标代码 {{input.code_path}}，识别坏味道：过长函数、重复代码、过深嵌套、发散/霰弹式修改、职责混杂。列出位置与证据。',
          next: [{ when: '', to: 'b2' }],
        }),
        block({
          id: 'b2',
          kind: 'decision',
          title: '是否有测试保护',
          condition: '目标代码存在可运行的单元测试覆盖',
          next: [
            { when: '是', to: 'b3' },
            { when: '否', to: 'b4' },
          ],
        }),
        block({
          id: 'b3',
          kind: 'prompt',
          title: '输出重构方案',
          prompt:
            '按优先级输出方案：坏味道、对应重构手法（如提取函数/引入参数对象/以多态取代条件）、预期收益、单步可验证的重构步骤序列，每步后运行测试。',
          next: [{ when: '', to: 'b5' }],
        }),
        block({
          id: 'b4',
          kind: 'step',
          title: '先补特征测试',
          steps: ['为现有行为编写特征测试固化当前输出', '再回到重构方案评估'],
          next: [{ when: '', to: 'b3' }],
        }),
        block({
          id: 'b5',
          kind: 'human',
          title: '方案评审',
          humanInstruction: '重构涉及接口变更或跨模块调整时，请人工确认方案后再实施',
        }),
      ],
    },
  },
  {
    slug: 'regex-explain',
    name: '正则解释与调试',
    description: '逐段解释正则表达式含义，标注陷阱（贪婪、回溯、边界），并给出测试样例验证。',
    category: '效率',
    tags: ['regex', 'explain', 'debug'],
    type: 'prompt',
    license: 'MIT',
    compatible_clients: CLIENTS,
    mcp_dependencies: [],
    current_version: 'v1.0.0',
    content: {
      entryBlockId: 'b1',
      blocks: [
        block({
          id: 'b1',
          kind: 'input',
          title: '待解释正则',
          name: 'regex',
          valueType: 'text',
          required: true,
          next: [{ when: '', to: 'b2' }],
        }),
        block({
          id: 'b2',
          kind: 'prompt',
          title: '逐段解释',
          prompt:
            '对正则 {{input.regex}} 逐 token 分段解释：匹配目标、量词贪婪性、分组是否捕获、锚点与边界。使用目标语言 {{input.language}} 的正则方言说明差异。',
          next: [{ when: '', to: 'b3' }],
        }),
        block({
          id: 'b3',
          kind: 'prompt',
          title: '陷阱与样例',
          prompt:
            '指出潜在问题：灾难性回溯、误匹配边界、多行/Unicode 开关影响；给出 3 个匹配与 3 个不匹配的测试样例及预期。若用户意图明确，附一条更简洁或更安全的等价写法。',
        }),
      ],
    },
  },
  {
    slug: 'sql-optimization',
    name: 'SQL 优化',
    description: '分析慢 SQL 的执行计划，给出索引设计、改写建议与前后成本对比。',
    category: '重构',
    tags: ['sql', 'database', 'index'],
    type: 'workflow',
    license: 'MIT',
    compatible_clients: CLIENTS,
    mcp_dependencies: [],
    current_version: 'v1.0.0',
    content: {
      entryBlockId: 'b1',
      blocks: [
        block({
          id: 'b1',
          kind: 'prompt',
          title: '读取执行计划',
          prompt:
            '对慢 SQL 使用 EXPLAIN（ANALYZE）获取执行计划，标注全表扫描、嵌套循环、排序/溢出到磁盘的节点。SQL：{{input.sql}}，表结构：{{input.schema}}',
          next: [{ when: '', to: 'b2' }],
        }),
        block({
          id: 'b2',
          kind: 'step',
          title: '逐项诊断',
          steps: ['过滤条件的选择性与现有索引匹配度', 'JOIN 顺序与连接键索引', 'SELECT * 与覆盖索引机会', '隐式类型转换与函数包裹列导致索引失效'],
          next: [{ when: '', to: 'b3' }],
        }),
        block({
          id: 'b3',
          kind: 'prompt',
          title: '输出优化方案',
          prompt:
            '输出：建议索引（含列顺序理由）、SQL 改写（如 EXISTS 替换 IN、分页游标化）与预期代价变化。区分「可直接执行」与「需要 DBA 评估（锁表/写放大）」两类建议。',
          next: [{ when: '', to: 'b4' }],
        }),
        block({
          id: 'b4',
          kind: 'human',
          title: '索引变更确认',
          humanInstruction: '创建索引会带来写入开销与在线 DDL 锁风险，请人工评估后在低峰期执行',
        }),
      ],
    },
  },
  {
    slug: 'api-design-review',
    name: 'API 设计评审',
    description: '按 RESTful 规范与一致性原则评审接口设计，输出资源建模、错误码与版本化改进项。',
    category: '开发流程',
    tags: ['api', 'rest', 'design-review'],
    type: 'workflow',
    license: 'MIT',
    compatible_clients: CLIENTS,
    mcp_dependencies: [],
    current_version: 'v1.0.0',
    content: {
      entryBlockId: 'b1',
      blocks: [
        block({
          id: 'b1',
          kind: 'prompt',
          title: '收集接口定义',
          prompt: '阅读待评审的接口定义（路由/DTO/OpenAPI）：{{input.api_spec}}，整理资源、方法与状态码清单。',
          next: [{ when: '', to: 'b2' }],
        }),
        block({
          id: 'b2',
          kind: 'step',
          title: '规范评审',
          steps: ['资源命名：名词复数、层级不超两层、无动词路径', 'HTTP 语义：方法幂等性、状态码准确、分页/过滤/排序约定', '错误结构：统一错误码与可定位的 message', '兼容性：破坏性变更是否走新版本/新字段'],
          next: [{ when: '', to: 'b3' }],
        }),
        block({
          id: 'b3',
          kind: 'decision',
          title: '是否存在破坏性变更',
          condition: '改动删除/重命名了对外字段或改变了既有语义',
          next: [
            { when: '是', to: 'b4' },
            { when: '否', to: 'b5' },
          ],
        }),
        block({
          id: 'b4',
          kind: 'human',
          title: '破坏性变更评审',
          humanInstruction: '存在破坏性变更，需人工评估迁移方案与客户端兼容窗口',
          next: [{ when: '', to: 'b5' }],
        }),
        block({
          id: 'b5',
          kind: 'prompt',
          title: '输出评审报告',
          prompt: '输出评审报告：结论（通过/有条件通过/驳回）、问题清单（按阻塞/建议分级）、改进示例（给出修改前后的路由或 DTO 片段）。',
        }),
      ],
    },
  },
  {
    slug: 'code-explain',
    name: '代码解释',
    description: '面向指定读者水平解释代码片段的功能、执行流程与设计意图，标注风险点。',
    category: '效率',
    tags: ['explain', 'onboarding', 'reading'],
    type: 'prompt',
    license: 'MIT',
    compatible_clients: CLIENTS,
    mcp_dependencies: [],
    current_version: 'v1.0.0',
    content: {
      entryBlockId: 'b1',
      blocks: [
        block({
          id: 'b1',
          kind: 'input',
          title: '目标代码',
          name: 'code',
          valueType: 'text',
          required: true,
          next: [{ when: '', to: 'b2' }],
        }),
        block({
          id: 'b2',
          kind: 'prompt',
          title: '结构化解释',
          prompt:
            '解释代码 {{input.code}}：先用一句话概括做什么；再按执行顺序分步说明关键逻辑；解释不直观的写法（位运算、闭包、并发原语等）。读者水平：{{input.reader_level}}',
          next: [{ when: '', to: 'b3' }],
        }),
        block({
          id: 'b3',
          kind: 'prompt',
          title: '上下文与风险',
          prompt:
            '补充：该代码依赖的外部契约（输入/输出/副作用），以及阅读中发现的潜在风险（边界、异常、竞态）——只标注，不顺手修改。',
        }),
      ],
    },
  },
  {
    slug: 'doc-translation',
    name: '文档翻译',
    description: '翻译技术文档，保留代码块、术语表与链接结构，输出术语对照表。',
    category: '写作',
    tags: ['translation', 'i18n', 'docs'],
    type: 'steps',
    license: 'MIT',
    compatible_clients: CLIENTS,
    mcp_dependencies: [],
    current_version: 'v1.0.0',
    content: {
      entryBlockId: 'b1',
      blocks: [
        block({
          id: 'b1',
          kind: 'input',
          title: '翻译设置',
          name: 'target_language',
          valueType: 'text',
          required: true,
          next: [{ when: '', to: 'b2' }],
        }),
        block({
          id: 'b2',
          kind: 'prompt',
          title: '建立术语表',
          prompt:
            '通读文档，提取技术术语与专有名词，确定译法（不翻译的保留原文：命令、API 名、库名），形成术语对照表。',
          next: [{ when: '', to: 'b3' }],
        }),
        block({
          id: 'b3',
          kind: 'prompt',
          title: '执行翻译',
          prompt:
            '将文档翻译为 {{input.target_language}}：代码块与命令保持原样，仅翻译注释；保留 Markdown 结构、锚点链接与 frontmatter key；语句贴合目标语言技术写作习惯，避免逐字直译。',
        }),
      ],
    },
  },
  {
    slug: 'weekly-report',
    name: '周报生成',
    description: '从任务看板与提交记录汇总本周进展、风险与下周计划，输出结构化周报。',
    category: '写作',
    tags: ['report', 'weekly', 'summary'],
    type: 'workflow',
    license: 'MIT',
    compatible_clients: CLIENTS,
    mcp_dependencies: [],
    current_version: 'v1.0.0',
    content: {
      entryBlockId: 'b1',
      blocks: [
        block({
          id: 'b1',
          kind: 'prompt',
          title: '收集素材',
          prompt:
            '汇总素材：本周完成的任务 {{task.title}} 及其状态、关联提交记录、遗留未办。补充人工输入：{{input.extra_notes}}',
          next: [{ when: '', to: 'b2' }],
        }),
        block({
          id: 'b2',
          kind: 'prompt',
          title: '撰写周报',
          prompt:
            '按「本周进展（结果导向，量化产出）/ 关键决策与变更 / 风险与阻塞（附需要的支持）/ 下周计划」四段撰写，控制在一屏以内，删除过程性描述只保留结果与影响。',
          next: [{ when: '', to: 'b3' }],
        }),
        block({
          id: 'b3',
          kind: 'human',
          title: '人工校对',
          humanInstruction: '周报代表团队对外沟通口径，发送前请人工校对事实与措辞',
        }),
      ],
    },
  },
  {
    slug: 'pr-description',
    name: 'PR 描述生成',
    description: '根据分支与主干 diff 生成 PR 描述：变更摘要、影响面、测试证据与回滚方式。',
    category: '开发流程',
    tags: ['pr', 'git', 'review'],
    type: 'prompt',
    license: 'MIT',
    compatible_clients: CLIENTS,
    mcp_dependencies: [],
    current_version: 'v1.0.0',
    content: {
      entryBlockId: 'b1',
      blocks: [
        block({
          id: 'b1',
          kind: 'prompt',
          title: '分析差异',
          prompt:
            '对比当前分支与主干的 diff 与提交列表，归纳变更动机、修改点与关联任务（{{task.title}}）。补充背景：{{input.context}}',
          next: [{ when: '', to: 'b2' }],
        }),
        block({
          id: 'b2',
          kind: 'prompt',
          title: '撰写 PR 描述',
          prompt:
            '输出 PR 描述模板：## 变更内容（要点式）、## 为什么（动机与方案取舍）、## 影响面（调用方/配置/数据）、## 测试（已运行的测试与结果，未覆盖项如实标注）、## 回滚方式。禁止编造未执行的测试结果。',
        }),
      ],
    },
  },
  {
    slug: 'coverage-gap-analysis',
    name: '覆盖率缺口分析',
    description: '结合覆盖率报告与代码风险度，找出值得补测的缺口并排定补测优先级。',
    category: '测试',
    tags: ['coverage', 'test', 'quality'],
    type: 'workflow',
    license: 'MIT',
    compatible_clients: CLIENTS,
    mcp_dependencies: [],
    current_version: 'v1.0.0',
    content: {
      entryBlockId: 'b1',
      blocks: [
        block({
          id: 'b1',
          kind: 'prompt',
          title: '读取覆盖率',
          prompt:
            '读取覆盖率报告（如 coverage-summary），列出行/分支覆盖率低于阈值的文件：{{input.coverage_report}}',
          next: [{ when: '', to: 'b2' }],
        }),
        block({
          id: 'b2',
          kind: 'step',
          title: '风险加权',
          steps: ['按变更频率（近期提交次数）加权', '按业务关键性（鉴权、资金、状态机）加权', '排除纯类型定义、常量等无需测试的文件'],
          next: [{ when: '', to: 'b3' }],
        }),
        block({
          id: 'b3',
          kind: 'prompt',
          title: '输出补测清单',
          prompt:
            '输出优先级排序的补测清单：文件、未覆盖分支描述、建议用例（happy path + 边界 + 异常）、预估收益。明确标注「不值得补测」的部分及理由，避免为数字而测。',
        }),
      ],
    },
  },
  {
    slug: 'incident-postmortem',
    name: '事故复盘',
    description: '按时间线梳理事故经过，定位根因（5 Whys），输出可执行的改进项与责任人。',
    category: '文档',
    tags: ['postmortem', 'incident', 'blameless'],
    type: 'workflow',
    license: 'MIT',
    compatible_clients: CLIENTS,
    mcp_dependencies: [],
    current_version: 'v1.0.0',
    content: {
      entryBlockId: 'b1',
      blocks: [
        block({
          id: 'b1',
          kind: 'prompt',
          title: '整理时间线',
          prompt:
            '根据告警记录、操作日志与沟通记录整理事故时间线：发现、响应、定位、恢复各环节的时间点与动作。事故概述：{{input.incident_summary}}',
          next: [{ when: '', to: 'b2' }],
        }),
        block({
          id: 'b2',
          kind: 'prompt',
          title: '根因分析',
          prompt:
            '用 5 Whys 追问到底：区分触发条件与系统性根因（流程、监控、架构），避免把根因归咎于个人操作失误。列出所有贡献因素。',
          next: [{ when: '', to: 'b3' }],
        }),
        block({
          id: 'b3',
          kind: 'prompt',
          title: '输出复盘报告',
          prompt:
            '按 blameless 模板输出：影响范围（量化）、时间线、根因、教训、改进项（每项含负责人、期限、验收标准，区分预防/检测/缓解三类）。',
          next: [{ when: '', to: 'b4' }],
        }),
        block({
          id: 'b4',
          kind: 'human',
          title: '改进项评审',
          humanInstruction: '改进项涉及跨团队排期与资源投入，请人工评审优先级后归档',
        }),
      ],
    },
  },
  {
    slug: 'log-analysis',
    name: '日志分析',
    description: '从错误日志中聚类问题模式，定位可疑代码路径并输出排查结论与证据链。',
    category: '效率',
    tags: ['logs', 'debugging', 'triage'],
    type: 'steps',
    license: 'MIT',
    compatible_clients: CLIENTS,
    mcp_dependencies: [],
    current_version: 'v1.0.0',
    content: {
      entryBlockId: 'b1',
      blocks: [
        block({
          id: 'b1',
          kind: 'input',
          title: '日志输入',
          name: 'logs',
          valueType: 'text',
          required: true,
          next: [{ when: '', to: 'b2' }],
        }),
        block({
          id: 'b2',
          kind: 'step',
          title: '聚类与降噪',
          steps: ['按错误签名（类型+位置）聚类去重', '统计各簇出现频次与首次/最后出现时间', '剔除与问题无关的噪声日志'],
          next: [{ when: '', to: 'b3' }],
        }),
        block({
          id: 'b3',
          kind: 'prompt',
          title: '定位与结论',
          prompt:
            '对主要错误簇：结合堆栈定位到源码位置，说明可疑原因与证据链（日志行 → 代码路径），给出下一步排查动作或修复假设。按影响面排定处理顺序。',
        }),
      ],
    },
  },

  // ================================ 2026-09 扩容：31 个高价值内置技能 ================================

  {
    slug: 'type-tightening',
    name: '类型收紧',
    description: '扫描 any/unknown/类型断言滥用，按风险排序给出收紧方案，公共类型变更需人工确认。',
    category: '重构',
    tags: ['typescript', 'types', 'type-safety'],
    type: 'workflow',
    license: 'MIT',
    compatible_clients: CLIENTS,
    mcp_dependencies: [],
    current_version: 'v1.0.0',
    content: {
      entryBlockId: 'b1',
      blocks: [
        inp('b1', '扫描范围', 'code_path', 'b2'),
        st('b2', '盘点类型逃逸点', [
          '列出显式 any、as 断言、非空断言 !、@ts-ignore 的位置与数量',
          '标记高危点：跨模块边界（函数入参/返回值、API 响应解析）上的逃逸',
          '低危点（测试文件、一次性脚本）单独归档不处理',
        ], 'b3'),
        dec('b3', '是否存在跨边界逃逸', 'any/断言出现在公共函数签名或外部数据解析路径上', 'b4', 'b5'),
        hum('b4', '公共类型变更确认', '收紧公共签名会波及调用方，请人工确认是否接受批量改动'),
        p('b5', '输出收紧方案', '按风险从高到低输出：位置、当前写法、建议写法（如用 zod/类型守卫替代断言、用 unknown 收窄 any）、影响文件数。每项给出可直接粘贴的代码片段；无法安全收紧的标注理由。'),
        out('b6', '收紧清单', 'tightening_plan'),
      ],
    },
  },
  {
    slug: 'dependency-upgrade-assessment',
    name: '依赖升级评估',
    description: '评估依赖升级的破坏面：读 changelog 与本仓库用法，输出风险分级与升级步骤。',
    category: '质量保障',
    tags: ['dependencies', 'upgrade', 'maintenance'],
    type: 'workflow',
    license: 'MIT',
    compatible_clients: CLIENTS,
    mcp_dependencies: [],
    current_version: 'v1.0.0',
    content: {
      entryBlockId: 'b1',
      blocks: [
        inp('b1', '待升级依赖', 'dependency_spec', 'b2'),
        p('b2', '收集升级信息', '对 {{input.dependency_spec}}：确认当前版本与目标版本；阅读官方 changelog/release notes，提取 breaking changes、废弃项与行为变更；按 semver 判断是否跨大版本。信息以官方 changelog 为准，查不到时明确说「未找到」而非编造。', 'b3'),
        st('b3', '对照本仓库用法', [
          'grep 本仓库对该依赖的全部调用点',
          '逐个调用点对照 breaking changes 清单，标记会受影响的代码',
          '检查配套依赖（插件、类型包、peer dependency）是否需要同步升级',
        ], 'b4'),
        dec('b4', '是否跨大版本且有 breaking change', '跨主版本且存在影响本仓库调用点的破坏性变更', 'b5', 'b6'),
        hum('b5', '大版本升级排期', '大版本升级需要专门的时间窗口与回归测试，请人工确认升级时机与回滚方案'),
        p('b6', '输出评估报告', '输出：结论（可安全升级/需改造后升级/暂缓）、受影响调用点清单（文件+行+需改动内容）、建议升级步骤（依赖变更→代码适配→回归范围）、锁版本不升级的风险。'),
      ],
    },
  },
  {
    slug: 'dead-code-cleanup',
    name: '死代码清理',
    description: '识别未被引用的导出、分支与文件，区分「确认可删」与「疑似动态引用」，删除前人工确认。',
    category: '重构',
    tags: ['dead-code', 'cleanup', 'refactor'],
    type: 'workflow',
    license: 'MIT',
    compatible_clients: CLIENTS,
    mcp_dependencies: [],
    current_version: 'v1.0.0',
    content: {
      entryBlockId: 'b1',
      blocks: [
        inp('b1', '清理范围', 'code_path', 'b2'),
        st('b2', '识别死代码', [
          '未被任何入口引用的导出符号、文件与目录',
          '恒假分支、被特性开关永久关闭的路径',
          '注释掉的代码块与遗留调试代码（console/debugger）',
        ], 'b3'),
        cons('b3', '排除动态引用', '反射、字符串拼接导入、配置驱动的路由/组件注册、外部脚本调用都可能构成隐式引用；静态分析判死的符号必须先检索字符串再定论'),
        dec('b4', '是否只含确认项', '清理清单全部符号均无动态引用证据', 'b5', 'b6'),
        p('b5', '生成清理 diff', '输出删除 diff 与删除后验证命令（构建+测试），一次提交只做删除不做逻辑修改。', 'b7'),
        hum('b6', '疑似项人工裁决', '清单包含疑似动态引用的符号，请人工逐项裁决保留或删除'),
        out('b7', '清理报告', 'cleanup_report'),
      ],
    },
  },
  {
    slug: 'error-handling-review',
    name: '错误处理审查',
    description: '审查错误传播路径：吞错、catch-all、未 await 的 rejection，输出按后果分级的修复清单。',
    category: '质量保障',
    tags: ['error-handling', 'review', 'reliability'],
    type: 'workflow',
    license: 'MIT',
    compatible_clients: CLIENTS,
    mcp_dependencies: [],
    current_version: 'v1.0.0',
    content: {
      entryBlockId: 'b1',
      blocks: [
        inp('b1', '审查范围', 'code_path', 'b2'),
        st('b2', '逐类检查', [
          '吞错：catch 后不记录、不上报、不上抛，调用方无从感知失败',
          'catch-all：捕获后笼统打日志继续执行，掩盖了本应中断的故障',
          '异步丢失：async 调用未 await/未 .catch，rejection 无人接住',
          '错误分类：对外错误是否区分用户可恢复与系统故障，是否泄漏内部堆栈给客户端',
        ], 'b3'),
        p('b3', '输出审查报告', '对 {{input.code_path}} 输出问题清单，每项含：位置、问题类型、失败场景推演（什么输入/故障会触发）、修复建议（补日志/上抛/重试/降级）。按「会造成静默数据错误」>「功能不可用但可感知」>「仅影响可观测性」分级排序。'),
        dec('b4', '是否存在静默数据错误风险', '发现吞错可能导致数据不一致或状态损坏', 'b5', 'b6'),
        hum('b5', '高危吞错确认', '存在可能造成静默数据错误的吞错路径，请人工确认修复优先级与历史数据是否需要修复'),
        out('b6', '审查报告', 'error_review'),
      ],
    },
  },
  {
    slug: 'concurrency-review',
    name: '并发审查',
    description: '审查共享状态、竞态与重试安全性，给出加锁/去重/幂等改造建议，高风险项人工确认。',
    category: '质量保障',
    tags: ['concurrency', 'race-condition', 'review'],
    type: 'workflow',
    license: 'MIT',
    compatible_clients: CLIENTS,
    mcp_dependencies: [],
    current_version: 'v1.0.0',
    content: {
      entryBlockId: 'b1',
      blocks: [
        inp('b1', '审查范围', 'code_path', 'b2'),
        st('b2', '竞态模式扫描', [
          '共享可变状态：跨请求/跨任务读写的模块级变量、缓存，是否需要锁或不可变快照',
          '读改写序列：先查后写（check-then-act）之间是否可能被并发插入',
          '重试放大：失败重试的写操作是否幂等，重复执行是否产生重复数据',
          '顺序假设：多个 await 之间是否有隐式顺序依赖，事务边界是否覆盖全部写操作',
        ], 'b3'),
        dec('b3', '是否存在资损级竞态', '竞态可能导致重复扣款/重复发放/库存超卖等资损后果', 'b4', 'b5'),
        hum('b4', '资损竞态人工确认', '发现潜在资损级竞态，请人工评估影响面并决定修复与是否需要核对历史数据'),
        p('b5', '输出审查报告', '每项输出：位置、竞态场景（用两条交错执行的时间线说明）、后果、改造建议（数据库唯一约束/乐观锁/分布式锁/幂等键/队列串行化），并标注改动的侵入程度。'),
        out('b6', '并发审查报告', 'concurrency_review'),
      ],
    },
  },
  {
    slug: 'api-contract-change-check',
    name: '接口契约变更检查',
    description: '对比接口定义前后差异，标记删除字段、类型收窄、语义变更等破坏点，输出兼容性结论。',
    category: '开发流程',
    tags: ['api', 'contract', 'compatibility'],
    type: 'workflow',
    license: 'MIT',
    compatible_clients: CLIENTS,
    mcp_dependencies: [],
    current_version: 'v1.0.0',
    content: {
      entryBlockId: 'b1',
      blocks: [
        inp('b1', '契约版本', 'contract_diff', 'b2'),
        st('b2', '差异分类', [
          '破坏性：删除/重命名字段、类型收窄、必填化、状态码语义变化、错误结构变更',
          '兼容性：新增可选字段、新增枚举值（标注消费方需容忍未知枚举）、新增端点',
          '存疑：默认值变化、排序/分页行为变化等文档未写明的隐式行为',
        ], 'b3'),
        dec('b3', '是否存在破坏性变更', '分类结果包含任何破坏性差异', 'b4', 'b5'),
        hum('b4', '破坏性变更评审', '存在破坏性契约变更，请人工确认：通知哪些消费方、是否保留旧字段过渡期、版本号如何推进'),
        p('b5', '输出检查结论', '输出差异清单（分类+影响方）与结论：可直发/需过渡期（双写或字段保留 N 个版本）/需新版本端点。对每条破坏性变更给出兼容写法示例。'),
        out('b6', '契约检查结论', 'contract_check'),
      ],
    },
  },
  {
    slug: 'slow-api-diagnosis',
    name: '慢接口定位',
    description: '沿调用链拆解慢接口耗时：数据库、外部调用、序列化、锁，输出瓶颈证据与优化排序。',
    category: '效率',
    tags: ['performance', 'api', 'latency'],
    type: 'steps',
    license: 'MIT',
    compatible_clients: CLIENTS,
    mcp_dependencies: [],
    current_version: 'v1.0.0',
    content: {
      entryBlockId: 'b1',
      blocks: [
        inp('b1', '慢接口信息', 'api_info', 'b2'),
        st('b2', '建立耗时分解', [
          '获取链路追踪或打点数据（没有则建议补临时打点），拆出各段耗时：DB 查询、外部 HTTP、CPU 计算、序列化',
          '数据库段重点查 N+1（循环内逐条查询）、缺失索引导致的顺序扫描、一次性捞取大结果集',
          '外部段重点查串行可并行、无超时无熔断、每次请求重复建立连接',
        ], 'b3'),
        p('b3', '输出定位结论', '对 {{input.api_info}} 输出：耗时瀑布（各段占比）、瓶颈证据（引用具体查询/调用与数据量）、优化选项按「改动小收益大」排序（如批量查询替代循环查询、加缓存、并行化、分页），并说明每项的预期收益与风险。阈值标准按项目 SLO 约定，未约定时以「本接口自身分解中占比 >30% 的段」为瓶颈。'),
      ],
    },
  },
  {
    slug: 'idempotency-check',
    name: '幂等性检查',
    description: '检查写接口在重试/重复提交下是否产生重复副作用，输出幂等键设计与缺失清单。',
    category: '质量保障',
    tags: ['idempotency', 'api', 'reliability'],
    type: 'workflow',
    license: 'MIT',
    compatible_clients: CLIENTS,
    mcp_dependencies: [],
    current_version: 'v1.0.0',
    content: {
      entryBlockId: 'b1',
      blocks: [
        inp('b1', '接口范围', 'api_scope', 'b2'),
        st('b2', '逐接口判定', [
          '列出范围内的全部写操作（POST/PUT/消息消费者/定时任务）',
          '推演重复执行场景：客户端超时重试、消息重复投递、用户双击、任务并发调度',
          '判定每个接口的副作用是否可重复：创建类是否有唯一键/幂等键，扣减类是否可重入，通知类是否会重发',
        ], 'b3'),
        p('b3', '输出检查报告', '对每个接口输出：结论（天然幂等/需幂等保护/不适用）、缺失保护时的事故场景、建议方案（客户端生成幂等键 + 服务端唯一约束是最优先方案；其次条件更新/状态机限制）。方案需落到具体表与字段层面描述，字段命名按项目约定。'),
        dec('b4', '是否涉及资金或库存', '范围包含支付、退款、库存扣减等资金/库存接口', 'b5', 'b6'),
        hum('b5', '资损接口确认', '资金/库存接口的幂等改造需人工评审方案并安排对账验证'),
        out('b6', '幂等检查报告', 'idempotency_report'),
      ],
    },
  },
  {
    slug: 'db-migration-review',
    name: '数据库迁移评审',
    description: '评审数据库迁移脚本：锁表风险、可回滚性、新旧版本共存兼容性，高危操作人工把关。',
    category: '数据',
    tags: ['database', 'migration', 'ddl'],
    type: 'workflow',
    license: 'MIT',
    compatible_clients: CLIENTS,
    mcp_dependencies: [],
    current_version: 'v1.0.0',
    content: {
      entryBlockId: 'b1',
      blocks: [
        inp('b1', '迁移脚本', 'migration_sql', 'b2'),
        st('b2', '逐项评审', [
          '锁与耗时：大表加列/加索引/改类型，评估执行时长与锁行为；大表操作应采用「新增列→回填→切换」的分步策略而非原地改',
          '可回滚性：每个 up 是否有对应 down；删列删表不可逆，必须先确认数据不再被读',
          '共存兼容：迁移执行期间新旧两个版本的应用同时在线，schema 必须同时兼容两者（先加后删、禁止一步重命名）',
          '回填脚本：是否分批限速，避免大事务与主从延迟',
        ], 'b3'),
        dec('b3', '是否含不可逆或大表操作', '存在 DROP/改类型/大表在线变更', 'b4', 'b5'),
        hum('b4', '高危迁移审批', '迁移含不可逆或长锁风险操作，请人工评估执行窗口、备份与回滚预案后方可上线'),
        out('b5', '迁移评审结论', 'migration_review'),
      ],
    },
  },
  {
    slug: 'accessibility-audit',
    name: '可访问性检查',
    description: '按 WCAG 核心项检查页面：语义结构、键盘可达、对比度、表单标签，输出分级问题清单。',
    category: '质量保障',
    tags: ['a11y', 'accessibility', 'wcag', 'frontend'],
    type: 'workflow',
    license: 'MIT',
    compatible_clients: CLIENTS,
    mcp_dependencies: [],
    current_version: 'v1.0.0',
    content: {
      entryBlockId: 'b1',
      blocks: [
        inp('b1', '页面/组件范围', 'ui_scope', 'b2'),
        st('b2', '核心项检查', [
          '语义与结构：标题层级是否连续、按钮/链接是否用原生元素而非 div 加点击事件、图片是否有 alt（装饰图用空 alt）',
          '键盘可达：所有交互元素可 Tab 到达且顺序合理、弹窗焦点是否困在弹窗内、可见焦点样式未被移除',
          '表单：每个输入有关联的 label、错误提示不只靠颜色传达',
          '对比度：正文文字对比度是否达标（WCAG AA 常规文本 4.5:1，大字 3:1）',
        ], 'b3'),
        p('b3', '输出检查报告', '对 {{input.ui_scope}} 输出问题清单：位置、违反的检查项、对哪类用户造成障碍、修复建议（给出组件改法）。按「完全无法使用」>「能用但费力」>「体验改进」分级。无法静态判断的项目（如实际对比度、屏幕阅读器表现）列为「需手工验证」并给出验证步骤。'),
        out('b4', '可访问性报告', 'a11y_report'),
      ],
    },
  },
  {
    slug: 'frontend-performance-budget',
    name: '前端性能预算',
    description: '为页面核对性能预算：包体积、核心 Web 指标、加载瀑布，超标项给出治理方案。',
    category: '重构',
    tags: ['performance', 'bundle', 'core-web-vitals', 'frontend'],
    type: 'steps',
    license: 'MIT',
    compatible_clients: CLIENTS,
    mcp_dependencies: [],
    current_version: 'v1.0.0',
    content: {
      entryBlockId: 'b1',
      blocks: [
        inp('b1', '页面与构建产物', 'build_info', 'b2'),
        st('b2', '逐项核对', [
          '包体积：对比构建产物报告，找出体积突增的依赖与重复打包的库（同一库多版本共存）',
          '核心 Web 指标：LCP（最大内容绘制）、INP（交互延迟）、CLS（布局偏移）实测值；指标良好阈值参考 LCP<2.5s、INP<200ms、CLS<0.1，项目有自定预算以预算为准',
          '加载瀑布：首屏是否被未用的 JS 阻塞、图片是否懒加载且尺寸合理、字体是否阻塞渲染',
        ], 'b3'),
        p('b3', '输出治理清单', '对 {{input.build_info}} 输出：预算对照表（指标/实测/预算/结论）、超标项归因（哪个依赖/资源）、治理方案排序（代码分割、按需引入、图片压缩与 CDN、移除死依赖），每项标注预期收益量级与改动成本。'),
      ],
    },
  },
  {
    slug: 'component-split',
    name: '组件拆分建议',
    description: '识别过长/多职责组件，依据状态归属与复用边界给出拆分方案与迁移步骤。',
    category: '重构',
    tags: ['frontend', 'react', 'refactor', 'component'],
    type: 'workflow',
    license: 'MIT',
    compatible_clients: CLIENTS,
    mcp_dependencies: [],
    current_version: 'v1.0.0',
    content: {
      entryBlockId: 'b1',
      blocks: [
        inp('b1', '目标组件', 'component_path', 'b2'),
        st('b2', '识别拆分信号', [
          '体量信号：单个文件行数明显超出项目惯例、render 内嵌套层级过深',
          '职责信号：一个组件同时承担取数、状态管理、布局、展示；props 超过约 8 个且多数是透传',
          '状态信号：useState 集群中存在总是同时变化、可合并为对象的组；存在可以下沉到子组件的局部状态',
        ], 'b3'),
        p('b3', '输出拆分方案', '给出目标结构：容器组件（取数+状态）与展示子组件的职责划分、各子组件的 props 定义、需提升或下沉的状态清单、自定义 Hook 的提取点（数据获取、防抖等横切逻辑）。拆分必须每步可独立验证（先提取纯展示叶子，再逐层上提），给出步骤序列。'),
        dec('b4', '是否为跨页面复用组件', '拆分后的组件会被多个页面/模块复用', 'b5', 'b6'),
        hum('b5', '复用 API 评审', '将成为公共组件的 props API 是对外契约，请人工评审命名与边界后再实施'),
        out('b6', '拆分方案', 'split_plan'),
      ],
    },
  },
  {
    slug: 'data-migration-reconciliation',
    name: '数据迁移核对',
    description: '设计并执行新旧存储的数据核对：总量、分片计数、抽样比对、金额勾稽，差异零容忍流程。',
    category: '数据',
    tags: ['data', 'migration', 'reconciliation'],
    type: 'workflow',
    license: 'MIT',
    compatible_clients: CLIENTS,
    mcp_dependencies: [],
    current_version: 'v1.0.0',
    content: {
      entryBlockId: 'b1',
      blocks: [
        inp('b1', '迁移上下文', 'migration_context', 'b2'),
        st('b2', '分层核对', [
          '总量层：新旧存储各业务表的行数对比（注意剔除软删除/过滤条件的口径差异，先核对口径再核对数字）',
          '分片层：按时间窗/主键区间分片计数，把差异定位到具体分片',
          '抽样层：每分片随机抽样逐字段比对；枚举值映射、时区/精度截断是最常见差异源',
          '勾稽层：金额、库存等按业务恒等式核对（如明细之和=汇总、借贷平衡）',
        ], 'b3'),
        dec('b3', '核对是否全部通过', '四层核对均无差异（或差异已逐条归因为已确认的合法转换）', 'b5', 'b4'),
        hum('b4', '差异人工裁决', '存在未解释差异：冻结切换，逐条定位差异原因（漏迁/重复/转换错误）后人工裁决处理方案'),
        p('b5', '输出核对报告', '输出核对矩阵（层级/范围/结果/差异说明）、已确认的合法转换清单（如金额单位从分到元）、切换建议与复核方式。核对 SQL/脚本一并提供以便他人复跑。'),
        out('b6', '核对报告', 'reconciliation_report'),
      ],
    },
  },
  {
    slug: 'report-metric-alignment',
    name: '报表口径核对',
    description: '核对多个报表/看板同名指标的口径：时间窗、去重、过滤、归属，输出口径对齐表。',
    category: '数据',
    tags: ['data', 'metrics', 'analytics', 'reporting'],
    type: 'steps',
    license: 'MIT',
    compatible_clients: CLIENTS,
    mcp_dependencies: [],
    current_version: 'v1.0.0',
    content: {
      entryBlockId: 'b1',
      blocks: [
        inp('b1', '待核对指标', 'metric_names', 'b2'),
        st('b2', '拆解口径维度', [
          '时间口径：自然日/滚动 24 小时、时区、统计截止时刻（T+1 还是实时）',
          '对象口径：去重键是什么（用户 ID/设备/账号）、匿名流量是否计入、测试数据是否剔除',
          '过滤口径：状态过滤（只算支付成功？）、异常值是否剔除、退款是否冲减',
          '归属口径：多归属场景按首次触点还是末次触点、跨天订单归属哪一天',
        ], 'b3'),
        p('b3', '输出对齐表', '对 {{input.metric_names}} 输出口径对齐表：指标名、各报表当前口径、差异点、建议统一口径（与数据负责人确认后生效）、统一前的换算说明。禁止在没有确认来源的情况下断言哪个口径是「正确」的。'),
      ],
    },
  },
  {
    slug: 'secret-leak-scan',
    name: '密钥泄露扫描',
    description: '扫描代码与提交历史中的硬编码凭据，命中即触发轮换流程，杜绝「删掉就行」的错觉。',
    category: '安全',
    tags: ['security', 'secrets', 'credentials'],
    type: 'workflow',
    license: 'MIT',
    compatible_clients: CLIENTS,
    mcp_dependencies: [],
    current_version: 'v1.0.0',
    content: {
      entryBlockId: 'b1',
      blocks: [
        inp('b1', '扫描范围', 'scan_scope', 'b2'),
        st('b2', '模式扫描', [
          '高置信模式：云厂商 AK/SK 前缀、私钥块（BEGIN PRIVATE KEY）、连接串内嵌密码、token 形态的随机串',
          '中置信：变量名含 password/secret/token/api_key 的字面量赋值',
          '配置文件与提交历史：.env 变体文件、被提交的构建产物、历史提交中的凭据（进过 git 历史即视为已泄露）',
        ], 'b3'),
        dec('b3', '是否存在真实凭据命中', '扫描发现疑似真实凭据（非测试占位值）', 'b4', 'b5'),
        hum('b4', '凭据轮换流程', '命中真实凭据：立即在对应平台吊销并轮换（仅删除代码不够，git 历史与日志中已可见），再清理代码与历史，请人工执行并确认轮换完成'),
        p('b5', '输出扫描报告', '输出：命中清单（位置/类型/置信度/是否已进 git 历史）、误报排除说明（如 placeholder、测试固定值）、预防建议（密钥移入环境变量/密钥管理服务、pre-commit 扫描钩子）。报告本身不得复现完整密钥值，只保留前 4 位指纹。'),
        out('b6', '扫描报告', 'secret_scan_report'),
      ],
    },
  },
  {
    slug: 'dependency-vuln-triage',
    name: '依赖漏洞分级',
    description: '对依赖 CVE 做可达性分级：不止看 CVSS 分数，结合使用方式判断实际暴露面并排定修复顺序。',
    category: '安全',
    tags: ['security', 'cve', 'dependencies'],
    type: 'workflow',
    license: 'MIT',
    compatible_clients: CLIENTS,
    mcp_dependencies: [],
    current_version: 'v1.0.0',
    content: {
      entryBlockId: 'b1',
      blocks: [
        inp('b1', '漏洞清单来源', 'vuln_report', 'b2'),
        st('b2', '逐条分级', [
          '基础信息：CVE 编号、CVSS 评分、受影响版本区间（以官方公告为准，不凭记忆）',
          '可达性：本仓库是否真的调用了受漏洞影响的代码路径（深层传递依赖里的漏洞函数未被使用时，实际风险显著低于评分）',
          '可利用性：触发条件是否需要特殊环境；有公开 exploit 的漏洞提级处理',
          '修复路径：是否存在已修复版本，升级是否引入 breaking change（联动依赖升级评估）',
        ], 'b3'),
        dec('b3', '是否存在紧急级漏洞', '存在可远程利用、有公开 exploit 且本仓库可达的漏洞', 'b4', 'b5'),
        hum('b4', '紧急漏洞响应', '存在紧急级漏洞：请人工确认立即升级窗口，必要时先启用缓解措施（WAF 规则/关闭受影响功能）'),
        p('b5', '输出分级报告', '输出修复排序列表：漏洞、等级（紧急/高/中/低 + 判定理由）、修复版本、升级代价、临时缓解措施。明确区分「评分高但不可达」与「评分低但可达」的条目。'),
        out('b6', '分级报告', 'vuln_triage'),
      ],
    },
  },
  {
    slug: 'authz-path-check',
    name: '越权路径检查',
    description: '枚举写操作与查询端点，逐个核对资源归属校验（水平/垂直越权），输出缺失清单。',
    category: '安全',
    tags: ['security', 'authorization', 'idor'],
    type: 'workflow',
    license: 'MIT',
    compatible_clients: CLIENTS,
    mcp_dependencies: [],
    current_version: 'v1.0.0',
    content: {
      entryBlockId: 'b1',
      blocks: [
        inp('b1', '端点范围', 'endpoint_scope', 'b2'),
        st('b2', '逐端点核对', [
          '水平越权（IDOR）：按 ID 取资源的地方，查询条件是否同时过滤归属者（如 accountId/orgId），还是仅凭 ID 直取',
          '垂直越权：管理端操作是否校验角色，普通用户能否通过直接调用接口绕过前端隐藏入口',
          '批量接口：批量查询/导出的过滤条件是否与单个接口一致，避免单个有校验、批量没有',
          '间接对象：用自增 ID 还是不可猜测 ID 只能增加成本，不能替代归属校验',
        ], 'b3'),
        p('b3', '输出检查报告', '对 {{input.endpoint_scope}} 输出：每端点的核对结论（有归属校验/缺失/存疑需运行时验证）、缺失项的复现推演（用两个不同账号的访问序列描述）、修复建议（在数据层统一加归属过滤优于每处手写 if）。运行时验证类条目标注「需渗透验证」。'),
        dec('b4', '是否确认存在越权', '确认存在可被直接利用的越权路径', 'b5', 'b6'),
        hum('b5', '越权漏洞响应', '确认越权属安全漏洞：请人工评估影响面、修复后排期，并按公司安全流程决定是否需要审计数据访问日志'),
        out('b6', '检查报告', 'authz_report'),
      ],
    },
  },
  {
    slug: 'release-checklist',
    name: '发布检查单',
    description: '按检查单逐项确认发布就绪：变更清单、迁移、配置、灰度与回滚，审批卡点人工放行。',
    category: '运维',
    tags: ['release', 'checklist', 'deploy'],
    type: 'workflow',
    license: 'MIT',
    compatible_clients: CLIENTS,
    mcp_dependencies: [],
    current_version: 'v1.0.0',
    content: {
      entryBlockId: 'b1',
      blocks: [
        inp('b1', '发布信息', 'release_info', 'b2'),
        st('b2', '发布前逐项核对', [
          '变更清单：本版本包含的 PR/任务与 {{task.title}} 关联内容，是否混入未 review 的提交',
          '数据与配置：待执行的数据库迁移已评审？新增环境变量在目标环境已配置？功能开关初始值正确？',
          '测试证据：CI 全绿？核心链路回归通过？未覆盖项已知晓并接受？',
          '预案：回滚版本与回滚步骤明确？数据库迁移是否可回滚或前向兼容？',
        ], 'b3'),
        dec('b3', '是否存在未决项', '存在未完成的检查项或未接受的测试缺口', 'b4', 'b5'),
        p('b4', '输出阻塞清单', '列出阻塞项、责任人与解除条件，终止本次发布流程。', 'b6'),
        hum('b5', '发布放行审批', '检查单已就绪，请发布负责人人工确认放行（放行即表示接受上述检查项的真实性）'),
        p('b6', '输出发布摘要', '输出发布摘要：版本、变更清单、灰度计划（先小流量观察核心指标再全量）、回滚触发条件与回滚步骤。'),
        out('b7', '发布摘要', 'release_summary'),
      ],
    },
  },
  {
    slug: 'rollback-plan',
    name: '回滚预案',
    description: '为发布制定可执行的回滚预案：触发条件、代码回滚、数据兼容、职责分工，演练验证。',
    category: '运维',
    tags: ['rollback', 'deploy', 'sre'],
    type: 'steps',
    license: 'MIT',
    compatible_clients: CLIENTS,
    mcp_dependencies: [],
    current_version: 'v1.0.0',
    content: {
      entryBlockId: 'b1',
      blocks: [
        inp('b1', '发布上下文', 'release_context', 'b2'),
        st('b2', '预案要素', [
          '触发条件：量化且无需讨论即可执行（错误率/延迟超过项目 SLO 约定的阈值并持续 N 分钟），明确谁有权宣布回滚',
          '代码回滚：回滚到的版本号、回滚命令与耗时；确认旧版本代码与新 schema 前向兼容（新列可空/新增字段旧代码可忽略）',
          '数据回滚：迁移已上线的部分如何处理（前向修复优于回滚 DDL）；写入的新数据旧版本如何忽略',
          '外围：缓存与消息队列中残留的新版本数据、第三方回调期间的兼容',
        ], 'b3'),
        p('b3', '输出预案文档', '对 {{input.release_context}} 输出一页纸预案：触发条件表、执行步骤（每步含负责人角色与预期耗时，总耗时目标按项目约定）、回滚后验证清单、演练安排。任何一步写不出具体命令的，标注「待补充」并指定补齐人。'),
      ],
    },
  },
  {
    slug: 'alert-noise-reduction',
    name: '告警降噪',
    description: '对告警做聚类归因：识别告警风暴、阈值抖动与无主告警，输出分级路由与治理清单。',
    category: '运维',
    tags: ['alerting', 'oncall', 'observability'],
    type: 'workflow',
    license: 'MIT',
    compatible_clients: CLIENTS,
    mcp_dependencies: [],
    current_version: 'v1.0.0',
    content: {
      entryBlockId: 'b1',
      blocks: [
        inp('b1', '告警数据', 'alert_data', 'b2'),
        st('b2', '归因分类', [
          '风暴源：同一故障引发的告警级联（根因告警 + 上游超时连带的下游告警），按时间与依赖关系聚类',
          '抖动源：指标在阈值附近震荡导致的反复触发，应加持续时间窗或改用环比/恢复通知',
          '僵尸告警：近 30 天从未被处理过的告警——要么没人负责，要么阈值失效，逐条裁决',
          '缺主告警：没有明确 owner 与处理手册（runbook）的告警',
        ], 'b3'),
        p('b3', '输出治理方案', '对 {{input.alert_data}} 输出：聚类结论（每个风暴标注疑似根因）、逐条处置建议（调阈值/加抑制规则/合并分组/删除）、按「P0 唤醒电话/P1 即时消息/P2 工作时段」的分级路由表。删除告警必须给出替代的可观测手段（如仪表盘），不允许静默消灭信号。'),
        dec('b4', '是否需要删除或合并在用告警', '治理方案包含删除已有告警规则', 'b5', 'b6'),
        hum('b5', '告警变更确认', '删除/合并告警会改变值班同学的感知，请值班负责人确认后生效'),
        out('b6', '治理方案', 'alert_tuning'),
      ],
    },
  },
  {
    slug: 'code-review-response',
    name: '审查意见应答',
    description: '逐条处理收到的 review 意见：分类采纳、有理有据地反驳、修订代码并回复。',
    category: '开发流程',
    tags: ['review', 'collaboration', 'git'],
    type: 'workflow',
    license: 'MIT',
    compatible_clients: CLIENTS,
    mcp_dependencies: [],
    current_version: 'v1.0.0',
    content: {
      entryBlockId: 'b1',
      blocks: [
        inp('b1', '审查意见', 'review_comments', 'b2'),
        st('b2', '逐条分类', [
          '采纳：直接修改，回复修改 commit 或位置',
          '澄清：意见基于误解，补充上下文礼貌说明，不改代码',
          '异议：意见成立但代价更大（如性能与可读性权衡），给出数据/依据提出替代方案',
          '延后：合理但超出本次范围，登记为后续任务并回复跟进计划',
        ], 'b3'),
        cons('b3', '回复基调', '对代码不对人：反驳只针对技术依据，引用规范/基准数据/既有约定；禁止使用情绪化措辞；拿不准的一律先询问而非争论'),
        dec('b4', '是否存在实质性异议', '存在拟反驳或延后的意见', 'b5', 'b6'),
        hum('b5', '异议沟通确认', '对实质性异议：建议先在会下/IM 与 reviewer 对齐再公开回复，避免 PR 里拉锯'),
        p('b6', '输出应答草稿', '为任务「{{task.title}}」逐条输出回复草稿与对应代码修订说明；采纳项附修改后的代码位置索引。'),
        out('b7', '应答草稿', 'review_responses'),
      ],
    },
  },
  {
    slug: 'requirement-breakdown',
    name: '需求拆解',
    description: '把需求描述拆为可排期的任务树：识别角色、边界与依赖，歧义点回给需求方澄清。',
    category: '开发流程',
    tags: ['planning', 'requirement', 'breakdown'],
    type: 'workflow',
    license: 'MIT',
    compatible_clients: CLIENTS,
    mcp_dependencies: [],
    current_version: 'v1.0.0',
    content: {
      entryBlockId: 'b1',
      blocks: [
        inp('b1', '需求描述', 'requirement', 'b2'),
        st('b2', '拆解', [
          '识别角色与用例：谁在什么场景下做什么，产出用例清单',
          '按「数据模型变更 / 后端逻辑 / 前端界面 / 配置与发布」四个轴拆任务，每个任务控制在可单日完成的粒度',
          '标注任务间依赖与可并行的部分，识别需要技术预研的点',
        ], 'b3'),
        dec('b3', '是否存在歧义', '需求中存在未定义的行为（异常分支、权限边界、数据口径等）', 'b4', 'b5'),
        hum('b4', '需求方澄清', '将歧义点整理成问题清单回给需求方确认，禁止自行脑补默认行为后排期'),
        p('b5', '输出任务树', '对需求「{{task.title}}」输出：任务树（每项含验收要点与预估量级：S/M/L）、依赖图、开放问题清单、明确排除在范围外的内容（防蔓延）。'),
        out('b6', '任务树', 'task_tree'),
      ],
    },
  },
  {
    slug: 'acceptance-criteria-generation',
    name: '验收标准生成',
    description: '为需求逐条生成 Given/When/Then 验收标准，覆盖正常、边界与异常路径，交需求方确认。',
    category: '开发流程',
    tags: ['acceptance', 'bdd', 'quality'],
    type: 'workflow',
    license: 'MIT',
    compatible_clients: CLIENTS,
    mcp_dependencies: [],
    current_version: 'v1.0.0',
    content: {
      entryBlockId: 'b1',
      blocks: [
        inp('b1', '需求描述', 'requirement', 'b2'),
        st('b2', '生成验收标准', [
          '每个用例按 Given（前置）/When（操作）/Then（可观察结果）三段式书写',
          '强制覆盖：正常路径、每个输入的边界值、权限不足/网络失败/并发冲突等异常路径',
          '结果必须可观察可判定：写「订单状态变为已取消且库存 +1」，不写「功能正常」',
        ], 'b3'),
        dec('b3', '是否存在无法判定的标准', '存在依赖外部行为或未定义细节、无法写成可判定条件的条目', 'b4', 'b5'),
        hum('b4', '标准澄清', '无法判定的条目列出待澄清问题，请需求方确认后再冻结验收标准'),
        out('b5', '验收标准', 'acceptance_criteria'),
      ],
    },
  },
  {
    slug: 'risk-register',
    name: '风险登记',
    description: '为项目/版本建立风险登记册：概率×影响评级、缓解与应急措施、责任人与复审节奏。',
    category: '开发流程',
    tags: ['risk', 'project-management', 'planning'],
    type: 'steps',
    license: 'MIT',
    compatible_clients: CLIENTS,
    mcp_dependencies: [],
    current_version: 'v1.0.0',
    content: {
      entryBlockId: 'b1',
      blocks: [
        inp('b1', '项目上下文', 'project_context', 'b2'),
        st('b2', '识别与评级', [
          '从五个来源扫风险：技术（新依赖/架构变更）、进度（外部依赖/关键人）、数据（迁移/合规）、外部（第三方接口变更）、运维（发布窗口/容量）',
          '每条风险评概率（高/中/低）与影响（高/中/低），两者皆高者必须有名有姓的缓解措施',
          '区分缓解措施（降低概率）与应急预案（降低影响），应急措施要写到可执行',
        ], 'b3'),
        p('b3', '输出登记册', '对 {{input.project_context}} 输出风险登记册表格：编号、风险描述、概率、影响、级别、缓解措施、应急预案、责任人（角色）、复审日期。级别高但无法给出可执行缓解措施的风险，单独标红提请升级决策。'),
      ],
    },
  },
  {
    slug: 'changelog-generation',
    name: '变更日志生成',
    description: '从提交与合并记录生成 Keep a Changelog 风格的变更日志，破坏性变更醒目标注。',
    category: '写作',
    tags: ['changelog', 'release-notes', 'git'],
    type: 'workflow',
    license: 'MIT',
    compatible_clients: CLIENTS,
    mcp_dependencies: [],
    current_version: 'v1.0.0',
    content: {
      entryBlockId: 'b1',
      blocks: [
        inp('b1', '版本范围', 'version_range', 'b2'),
        p('b2', '提取变更', '读取 {{input.version_range}} 范围内的提交与合并记录（git log），剔除纯杂项（格式化、CI 调整），把每条变更归入：Added（新功能）/ Changed（行为变更）/ Deprecated（即将移除）/ Removed / Fixed / Security。面向使用者描述「能用什么/有什么不同」，不照抄 commit message。', 'b3'),
        cons('b3', '忠实性约束', '只写提交记录中真实发生的变更；每条变更可追溯到具体提交；不确定影响面的标注「待确认」，禁止为了好看而泛化描述'),
        p('b4', '输出变更日志', '按 Keep a Changelog 格式输出本版本日志：破坏性变更置顶并用醒目标记，附迁移说明；末尾附完整提交哈希清单便于追溯。'),
        out('b5', '变更日志', 'changelog'),
      ],
    },
  },
  {
    slug: 'meeting-notes',
    name: '会议纪要',
    description: '从记录或口述整理会议纪要：决议、行动项（负责人+期限）、遗留问题，发出前人工确认。',
    category: '写作',
    tags: ['meeting', 'notes', 'collaboration'],
    type: 'workflow',
    license: 'MIT',
    compatible_clients: CLIENTS,
    mcp_dependencies: [],
    current_version: 'v1.0.0',
    content: {
      entryBlockId: 'b1',
      blocks: [
        inp('b1', '会议素材', 'meeting_material', 'b2'),
        st('b2', '整理结构', [
          '剥离过程性讨论，只保留三类信息：决议（含依据）、行动项、遗留问题',
          '每条行动项必须有负责人与截止时间；讨论中未落实的，列入遗留问题而非行动项',
          '有争议未达成一致的，如实记录各方立场，禁止写成假决议',
        ], 'b3'),
        p('b3', '输出纪要草稿', '输出纪要：会议主题（关联任务「{{task.title}}」）、参会人、决议清单、行动项表格（事项/负责人/期限/验收方式）、遗留问题。一句话能说清的不写两句。'),
        hum('b4', '发出前确认', '纪要代表与会各方的共识，请会议组织者核对决议与行动项归属后发出'),
        out('b5', '会议纪要', 'meeting_notes'),
      ],
    },
  },
  {
    slug: 'tech-design-review-comments',
    name: '技术方案评审意见',
    description: '对技术方案从可行性、风险、成本、备选四个维度出评审意见，结论分阻塞与建议。',
    category: '文档',
    tags: ['design-review', 'architecture', 'rfc'],
    type: 'workflow',
    license: 'MIT',
    compatible_clients: CLIENTS,
    mcp_dependencies: [],
    current_version: 'v1.0.0',
    content: {
      entryBlockId: 'b1',
      blocks: [
        inp('b1', '方案文档', 'design_doc', 'b2'),
        st('b2', '四维评审', [
          '可行性：方案是否覆盖异常路径与容量边界；关键假设是否有数据支撑',
          '风险：故障半径、数据一致性、回滚难度、对现有系统的侵入',
          '成本：开发与维护成本、引入的新依赖与运维负担',
          '备选：方案是否比较过至少一个替代路线；被否的备选理由是否站得住',
        ], 'b3'),
        cons('b3', '评审纪律', '每条意见必须指向方案中的具体段落并给出理由；不接受「建议考虑一下 XX」式无主语意见；与方案目标无关的个人偏好不写'),
        p('b4', '输出评审意见', '对 {{input.design_doc}} 输出：总体结论（通过/有条件通过/需要重做）、意见清单（每条含：位置、问题、依据、建议，并标注「阻塞」或「建议」）、需要补齐的数据或实验。'),
        out('b5', '评审意见', 'design_review'),
      ],
    },
  },
  {
    slug: 'flaky-test-triage',
    name: '不稳定测试分诊',
    description: '对 flaky 测试归因：时序依赖、共享状态、外部资源，输出隔离、修复或隔离处置方案。',
    category: '测试',
    tags: ['flaky', 'test', 'ci'],
    type: 'workflow',
    license: 'MIT',
    compatible_clients: CLIENTS,
    mcp_dependencies: [],
    current_version: 'v1.0.0',
    content: {
      entryBlockId: 'b1',
      blocks: [
        inp('b1', '失败用例信息', 'failing_tests', 'b2'),
        st('b2', '归因分析', [
          '时序类：依赖 sleep/固定延时、竞态、未等待异步完成——优先改为显式等待/确定性断言',
          '状态类：用例间共享可变状态（数据库、全局单例、文件系统），用例顺序影响结果',
          '环境类：依赖真实网络/时钟/随机数，未注入 mock',
          '复核：连续重跑 N 次区分「稳定失败」（真 bug）与「偶发失败」（flaky），N 按项目 CI 约定',
        ], 'b3'),
        dec('b3', '是稳定失败还是偶发', '复跑结果为稳定失败', 'b4', 'b5'),
        p('b4', '按缺陷处理', '稳定失败即真实缺陷：转缺陷修复流程，回退引发失败的合并（如适用）。', 'b6'),
        p('b5', '输出处置方案', '对 {{input.failing_tests}} 逐条输出：归因分类、证据、处置（修复改造/加入隔离清单限期修复/删除并说明理由）。禁止用「自动重试通过」长期掩盖 flaky——重试只做缓冲，必须配限期修复任务。'),
        out('b6', '分诊结论', 'flaky_triage'),
      ],
    },
  },
  {
    slug: 'test-data-generation',
    name: '测试数据构造',
    description: '生成覆盖边界与异常的测试数据：等价类划分、真实感字段、PII 脱敏，输出即用数据集。',
    category: '测试',
    tags: ['test-data', 'fixtures', 'privacy'],
    type: 'workflow',
    license: 'MIT',
    compatible_clients: CLIENTS,
    mcp_dependencies: [],
    current_version: 'v1.0.0',
    content: {
      entryBlockId: 'b1',
      blocks: [
        inp('b1', '目标模型', 'data_model', 'b2'),
        st('b2', '构造数据集', [
          '按字段类型做等价类与边界值：空值、最小/最大长度、特殊字符（emoji、引号、换行）、时区边界（如 23:59:59 与次日 00:00）',
          '业务规则对应的异常组合：过期+已使用、已删除+再次操作等非法状态组合',
          '体感真实：姓名/地址等用符合格式的虚构值，让数据在界面上看起来可信',
        ], 'b3'),
        cons('b3', '隐私红线', '禁止把生产环境真实用户数据直接用作测试数据；确需生产数据时必须先脱敏（姓名、证件、手机号、地址等可识别字段替换为不可逆映射的虚构值），脱敏规则需项目安全负责人认可'),
        p('b4', '输出数据集', '对 {{input.data_model}} 输出可直接使用的数据集（按项目既有 fixture 格式），每条数据标注覆盖的用例编号；附边界值取舍说明。'),
        out('b5', '测试数据集', 'test_dataset'),
      ],
    },
  },
  {
    slug: 'env-config-check',
    name: '环境配置检查',
    description: '对比各环境配置差异：缺失项、多余项、默认值漂移与疑似敏感值，发布前跑一遍。',
    category: '部署',
    tags: ['config', 'environment', 'deploy'],
    type: 'steps',
    license: 'MIT',
    compatible_clients: CLIENTS,
    mcp_dependencies: [],
    current_version: 'v1.0.0',
    content: {
      entryBlockId: 'b1',
      blocks: [
        inp('b1', '环境与配置来源', 'env_sources', 'b2'),
        st('b2', '逐项核对', [
          '代码扫描：汇总代码实际读取的全部配置键（环境变量/配置文件），与各环境实际配置对比',
          '缺失项：新功能依赖的配置在某环境不存在——上线后会取到空值或默认值',
          '漂移项：同名配置在不同环境的语义性差异（如超时时间数量级不同），确认是有意区分还是遗漏',
          '敏感值：配置中疑似明文密码/密钥的，只报告键名与指纹，不复现值，并提示改用密钥管理',
        ], 'b3'),
        p('b3', '输出检查报告', '对 {{input.env_sources}} 输出差异矩阵：配置键 × 环境，标注缺失/漂移/敏感；给出每个缺失项建议的取值来源（新配置需提供默认值是否安全带兜底的判断）。'),
      ],
    },
  },
  {
    slug: 'onboarding-guide',
    name: '新人上手指南',
    description: '从仓库与文档生成按周排期的新人上手路径：环境搭建、核心链路、首次任务建议。',
    category: '文档',
    tags: ['onboarding', 'docs', 'team'],
    type: 'steps',
    license: 'MIT',
    compatible_clients: CLIENTS,
    mcp_dependencies: [],
    current_version: 'v1.0.0',
    content: {
      entryBlockId: 'b1',
      blocks: [
        inp('b1', '项目路径', 'project_path', 'b2'),
        st('b2', '推导上手路径', [
          '环境搭建：从构建脚本与 README 提取真实的安装/启动/测试命令（不得编造命令），列出必备环境变量与外部服务依赖',
          '架构导览：按目录结构归纳分层与职责，标注 3-5 条「读懂本项目必读」的核心文件/模块',
          '核心链路：挑一条最有代表性的业务链路，串起从前端入口到数据落库的代码路径',
        ], 'b3'),
        p('b3', '输出指南', '对 {{input.project_path}} 输出按周排期的上手指南：第 1 周环境与运行、第 2 周核心链路与代码导读、第 3 周首次任务建议（从任务看板选一个典型小任务）。命令全部来自真实脚本；文档缺失的部分标注「待团队补充」并指明该问谁。'),
      ],
    },
  },
];
